locals {
  location_code = {
    "East US"              = "eus"
    "East US 2"            = "eus2"
    "West US"              = "wus"
    "West US 2"            = "wus2"
    "West US 3"            = "wus3"
    "Central US"           = "cus"
    "North Central US"     = "ncus"
    "South Central US"     = "scus"
    "West Central US"      = "wcus"
    "North Europe"         = "neu"
    "West Europe"          = "weu"
    "UK South"             = "uks"
    "UK West"              = "ukw"
    "France Central"       = "frc"
    "Germany West Central" = "gwc"
    "Switzerland North"    = "swn"
    "Norway East"          = "noe"
    "Sweden Central"       = "sec"
    "UAE North"            = "uaen"
    "Australia East"       = "aue"
    "Australia Southeast"  = "ause"
    "Japan East"           = "jpe"
    "Japan West"           = "jpw"
    "Korea Central"        = "krc"
    "Southeast Asia"       = "sea"
    "East Asia"            = "ea"
    "Central India"        = "cin"
    "South India"          = "sin"
    "West India"           = "win"
    "Jio India West"       = "jiowin"
    "Brazil South"         = "brs"
    "Canada Central"       = "cac"
    "Canada East"          = "cae"
  }
}
